version: '3'
services:
  web:
    build: .

    ports:
      - "5000:5000"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes" ]
    volumes:
      - C:\Users\lzocco\Fr05ty-hub\tradeshift:/data